### ISSUE TITLE
Failing to compile on windows

### ISSUE THREAD

**Issue by sirilvk** [emeryberger/Heap-Layers#21]
Failing to compile on VS 2015. Its looking for file stdalign.h. 

``
        cl /I. /Iinclude /Iinclude/util /Iinclude/hoard /Iinclude/superblocks /IHeap-Layers /D "NDEBUG" /D "_WINDOWS" /D "_WINDLL" /D "_WINRT_DLL" /D "_UNICODE" /D "UNICODE" /Zi /Ox /MD /nologo /W1 /WX- /Ox /Oi /Oy- /Gm- /EHsc /MD /GS /Gy /Zc:wchar_t /Zc:forScope /Gd /errorReport:queue "source\libhoard.cpp" "Heap-Layers\wrappers\winwrapper.cpp" "source\wintls.cpp" /GL /link /DLL /subsystem:console /OUT:libhoard.dll
libhoard.cpp
d:\dev\hoard\src\heap-layers\wrappers\ansiwrapper.h(9): fatal error C1083: Cannot open include file: 'stdalign.h': No such file or directory
``

**Comment by sirilvk** [comment]
The error was gone once i removed that header file from the ansiwrapper.h.

**Comment by emeryberger** [comment]
Thanks for the report! Fixed with https://github.com/emeryberger/Heap-Layers/commit/af72a121ffea005e0706b8b6ac80fe5bbb3ac0ae.
