### ISSUE TITLE
tprintf.h includes unistd.h and doesn't compile on Windows

### ISSUE THREAD

**Issue by blattersturm** [emeryberger/Heap-Layers#29]
Anything after 5808161bea26f6a172a4b0d6951a0dbcbb3e92bf no longer builds on Windows as tprintf.h assumes various things that won't exist on Windows.

**Comment by emeryberger** [comment]
Ugh, thanks. I will disable tprintf on Windows.

**Comment by emeryberger** [comment]
Including `tprintf.h` on Windows is now a NOP.
